// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: render.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace OfflineRender {
  public static partial class RenderService
  {
    static readonly string __ServiceName = "offlineRender.RenderService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::OfflineRender.StartRenderReq> __Marshaller_offlineRender_StartRenderReq = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::OfflineRender.StartRenderReq.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::OfflineRender.StartRenderRsp> __Marshaller_offlineRender_StartRenderRsp = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::OfflineRender.StartRenderRsp.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::OfflineRender.FinishRenderReq> __Marshaller_offlineRender_FinishRenderReq = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::OfflineRender.FinishRenderReq.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::OfflineRender.FinishRenderRsp> __Marshaller_offlineRender_FinishRenderRsp = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::OfflineRender.FinishRenderRsp.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::OfflineRender.StartRenderReq, global::OfflineRender.StartRenderRsp> __Method_StartRender = new grpc::Method<global::OfflineRender.StartRenderReq, global::OfflineRender.StartRenderRsp>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StartRender",
        __Marshaller_offlineRender_StartRenderReq,
        __Marshaller_offlineRender_StartRenderRsp);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::OfflineRender.FinishRenderReq, global::OfflineRender.FinishRenderRsp> __Method_FinishRender = new grpc::Method<global::OfflineRender.FinishRenderReq, global::OfflineRender.FinishRenderRsp>(
        grpc::MethodType.Unary,
        __ServiceName,
        "FinishRender",
        __Marshaller_offlineRender_FinishRenderReq,
        __Marshaller_offlineRender_FinishRenderRsp);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::OfflineRender.RenderReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of RenderService</summary>
    [grpc::BindServiceMethod(typeof(RenderService), "BindService")]
    public abstract partial class RenderServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::OfflineRender.StartRenderRsp> StartRender(global::OfflineRender.StartRenderReq request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::OfflineRender.FinishRenderRsp> FinishRender(global::OfflineRender.FinishRenderReq request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for RenderService</summary>
    public partial class RenderServiceClient : grpc::ClientBase<RenderServiceClient>
    {
      /// <summary>Creates a new client for RenderService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public RenderServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for RenderService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public RenderServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected RenderServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected RenderServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::OfflineRender.StartRenderRsp StartRender(global::OfflineRender.StartRenderReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StartRender(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::OfflineRender.StartRenderRsp StartRender(global::OfflineRender.StartRenderReq request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_StartRender, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::OfflineRender.StartRenderRsp> StartRenderAsync(global::OfflineRender.StartRenderReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StartRenderAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::OfflineRender.StartRenderRsp> StartRenderAsync(global::OfflineRender.StartRenderReq request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_StartRender, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::OfflineRender.FinishRenderRsp FinishRender(global::OfflineRender.FinishRenderReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return FinishRender(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::OfflineRender.FinishRenderRsp FinishRender(global::OfflineRender.FinishRenderReq request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_FinishRender, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::OfflineRender.FinishRenderRsp> FinishRenderAsync(global::OfflineRender.FinishRenderReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return FinishRenderAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::OfflineRender.FinishRenderRsp> FinishRenderAsync(global::OfflineRender.FinishRenderReq request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_FinishRender, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override RenderServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new RenderServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(RenderServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_StartRender, serviceImpl.StartRender)
          .AddMethod(__Method_FinishRender, serviceImpl.FinishRender).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, RenderServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_StartRender, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::OfflineRender.StartRenderReq, global::OfflineRender.StartRenderRsp>(serviceImpl.StartRender));
      serviceBinder.AddMethod(__Method_FinishRender, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::OfflineRender.FinishRenderReq, global::OfflineRender.FinishRenderRsp>(serviceImpl.FinishRender));
    }

  }
}
#endregion
